//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBeaconer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iBeaconer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgwin {
            get {
                object obj = ResourceManager.GetObject("bgwin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amory 394,F0 20 7D A6 4F A2 4E 98 80 24 BC 5B 71 E0 89 3E,1,49
        ///Amory A115,F0 20 7D A6 4F A2 4E 98 80 24 BC 5B 71 E0 89 3E,1,50
        ///Amory A128 ,F0 20 7D A6 4F A2 4E 98 80 24 BC 5B 71 E0 89 3E,1,51
        ///Amory A239AB,F0 20 7D A6 4F A2 4E 98 80 24 BC 5B 71 E0 89 3E,1,52
        ///Amory A239C,F0 20 7D A6 4F A2 4E 98 80 24 BC 5B 71 E0 89 3E,1,53
        ///Amory B105,F0 20 7D A6 4F A2 4E 98 80 24 BC 5B 71 E0 89 3E,1,54
        ///Amory B106,F0 20 7D A6 4F A2 4E 98 80 24 BC 5B 71 E0 89 3E,1,55
        ///Amory B142 ,F0 20 7D A6 4F A2 4E 98 80 24 BC 5B 71 E0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string positions {
            get {
                return ResourceManager.GetString("positions", resourceCulture);
            }
        }
    }
}
